name: Release

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag to release'
        required: true
        type: string

  workflow_call:
    inputs:
      tagName:
        description: 'Tag to release'
        required: true
        type: string

  push:
    tags:
      - 'v**'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: DeskflowAndroid
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag from input
        if: github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch'
        run: |
          echo "tag_name=${{ inputs.tagName }}" >> $GITHUB_ENV

      - name: Get tag from push
        if: github.event_name == 'push'
        run: |
          echo "tag_name=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Checkout tag
        run: |
          git fetch --tags
          git checkout tags/${{ env.tag_name }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build release APK/AAB
        run: |
          ./gradlew clean 
          ./gradlew bundleRelease
          ./gradlew assembleRelease

      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle-ready/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apks-ready/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.sign_aab.outputs.signedReleaseFile }}
            ${{ steps.sign_apk.outputs.signedReleaseFile }}
          tag_name: ${{ env.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Upload to Google Play
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
#          packageName: org.tfv.deskflow
#          releaseFiles: ${{ steps.sign_aab.outputs.signedReleaseFile }}
#          track: alpha
#          status: completed