name: Version

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Version type (major, minor, patch)'
        required: false
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: DeskflowAndroid
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Update AndroidManifest version, commit, and tag (if manual)
        run: |
          VERSION_TYPE="${{ github.event.inputs.versionType }}"
          ./scripts/bump-version.sh $VERSION_TYPE
          if [ $? -ne 0 ]; then
              echo "Failed to bump version"
              exit 1
          fi
          VERSION_PROPS="version.properties"
          MAJOR=$(grep '^major=' $VERSION_PROPS | cut -d'=' -f2)
          MINOR=$(grep '^minor=' $VERSION_PROPS | cut -d'=' -f2)
          PATCH=$(grep '^patch=' $VERSION_PROPS | cut -d'=' -f2)
          if [ -z "$MAJOR" ] || [ -z "$MINOR" ] || [ -z "$PATCH" ]; then
              echo "Version properties not found or incomplete"
              exit 1
          fi
          VERSION="$MAJOR.$MINOR.$PATCH"
          VERSION_CODE=$(echo $VERSION | awk -F. '{ printf("%d%02d%02d", $1,$2,$3) }')
          
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add $VERSION_PROPS
          git commit -m "chore: bump version (${VERSION_TYPE}) to ${VERSION} (${VERSION_CODE})"
          ./gradlew :app:assembleRelease
          
          git push origin master
          git tag v${VERSION}
          git push origin v${VERSION}

